name: CI/CD (API FastAPI + Streamlit)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  # ===================================================================
  #                BUILD + TEST : API FASTAPI (api.py)
  # ===================================================================
  build:
    name: Build & Test API
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies API
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Run tests
        run: |
          mkdir -p tests_reports
          pytest -q \
            --junitxml=tests_reports/junit.xml \
            --cov-report=term-missing \
            --cov-report=html:tests_reports/htmlcov

      - name: Upload test reports
        uses: actions/upload-artifact@v4
        with:
          name: tests-reports
          path: tests_reports/

      - name: Package API
        run: |
          zip -r api-bundle.zip \
            api.py \
            Procfile \
            requirements.txt \
            notebooks \
            -x "__pycache__/*"

      - name: Sauvegarde API
        uses: actions/upload-artifact@v4
        with:
          name: api-bundle
          path: api-bundle.zip

      - name: Package Dashboard
        run: |
          zip -r dashboard-bundle.zip \
            dashboard.py \
            Procfile \
            requirements.txt \
            -x "__pycache__/*"

      - name: Upload Dashboard bundle artifact
        uses: actions/upload-artifact@v4
        with:
          name: dashboard-bundle
          path: dashboard-bundle.zip

  # ===================================================================
  #                       DEPLOY API
  # ===================================================================
  deploy_api:
    name: Deploy API
    needs: build
    runs-on: ubuntu-latest

  # OBLIGATOIRE pour OIDC
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: api-bundle
          path: .
  
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-3
          # 👉 Utilise un rôle ASSUMABLE par GitHub (pas le service role EB)
          role-to-assume: arn:aws:iam::541372247838:role/GitHubActions-EB-Deploy
  
      - name: Deploy API
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_region: eu-west-3
          application_name: oc-scoring-api
          environment_name: oc-scoring-api-env
          version_label: api-${{ github.run_id }}-${{ github.sha }}
          deployment_package: ./api-bundle.zip
